### ISSUE TITLE
502异常

### ISSUE THREAD

**Issue by cky008** [Musicminion/e5-toolkit#1]
![CleanShot 2023-11-05 at 04 37 31@2x](https://github.com/Musicminion/e5-toolkit/assets/56156916/be26face-c0d7-45bb-a153-2bb2f4ff3ff3)
服务器环境：VM.Standard.E2.1.Micro - Canonical-Ubuntu-20.04-2023.09.28-0
使用docker安装，网址通过另一台VPS上的NginxProxyManager进行反代至运行docker容器的VPS的4200端口上
弱弱问下有办法解决吗TAT

**Comment by cky008** [comment]
![CleanShot 2023-11-05 at 04 42 36@2x](https://github.com/Musicminion/e5-toolkit/assets/56156916/74862275-700b-4d0f-a63d-bc16436610dd)
转为使用新前端则一直转圈（原本也是一直转圈），但新前端没有报502异常

**Comment by cky008** [comment]
没事了，更新Github程序后没点确认，令人感叹

**Comment by Musicminion** [comment]
诶嘿哈哈
